const notFound=()=>`<section class="not-found"><span class="not-found-code">404</span><h1>Page not found.</h1><p>The requested page does not exist in this KKGT website preview.</p><a class="button green route" href="${BASE}/">Return home</a></section>`;
const pages={'':home,about,'coffee-export':coffee,agrochemicals:agro,commodities:commoditiesPage,sustainability,quality,contact};
const meta={'':['Home','KKGT Import Export — Ethiopian coffee, agricultural inputs, farming, oilseeds and pulses.'],about:['About KKGT','Learn about KKGT Import Export and its agricultural business areas.'],'coffee-export':['Coffee Export','Explore KKGT Ethiopian green coffee origins and buyer information.'],agrochemicals:['Agrochemicals','Browse the KKGT agrochemical preview catalogue.'],commodities:['Oilseeds and Pulses','Explore Ethiopian oilseeds and pulses presented by KKGT.'],sustainability:['Farming and Sustainability','Review KKGT farming and sustainability content structure.'],quality:['Quality and Documentation','Review KKGT quality, traceability and documentation structure.'],contact:['Contact','Contact KKGT Import Export in Addis Ababa, Ethiopia.'],404:['Page not found','The requested page was not found in the KKGT website preview.']};
function routeFromLocation(){let p=location.pathname.replace(BASE,'').replace(/^\/|\/$/g,'');if(location.search.startsWith('?/')){p=location.search.slice(2).split('&')[0].replace(/~and~/g,'&');history.replaceState(null,'',BASE+'/'+p)}return p}
function pathFromLink(a){return a.getAttribute('href').replace(BASE,'').replace(/^\/|\/$/g,'')}
function bindRoutes(root=document){root.querySelectorAll('a.route:not([data-route-bound])').forEach(a=>{a.dataset.routeBound='true';a.addEventListener('click',e=>{e.preventDefault();closeMenu(false);render(pathFromLink(a),true)})})}
function render(requestedPath=routeFromLocation(),push=false){const known=Object.prototype.hasOwnProperty.call(pages,requestedPath);const path=known?requestedPath:'404';if(push){const target=requestedPath?BASE+'/'+requestedPath:BASE+'/';history.pushState(null,'',target)}const content=document.getElementById('content');content.innerHTML=known?pages[path]():notFound();const m=meta[path];const pagePath=known?(requestedPath?'/'+requestedPath:'/'):location.pathname.replace(BASE,'')||'/';const pageUrl=location.origin+BASE+pagePath;document.title=m[0]+' | KKGT Import Export';document.querySelector('meta[name="description"]').content=m[1];document.querySelector('meta[property="og:title"]').content=m[0]+' | KKGT Import Export';document.querySelector('meta[property="og:description"]').content=m[1];document.querySelector('meta[property="og:url"]').content=pageUrl;document.querySelector('link[rel="canonical"]').href=pageUrl;document.querySelectorAll('.nav a,.mobile-nav a').forEach(a=>{const active=known&&a.dataset.path===requestedPath;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});bindRoutes(content);observe(content);setupCatalog();setupContact();window.scrollTo({top:0,behavior:'auto'});content.focus({preventScroll:true})}
function observe(root){const nodes=root.querySelectorAll('.reveal');if(matchMedia('(prefers-reduced-motion: reduce)').matches){nodes.forEach(x=>x.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -4%'});nodes.forEach(x=>io.observe(x))}
function setupCatalog(){const search=document.getElementById('productSearch');if(!search)return;let filter='all';const apply=()=>{const q=search.value.trim().toLowerCase();document.querySelectorAll('#productGrid .product-card').forEach(c=>{c.hidden=!c.textContent.toLowerCase().includes(q)||(filter!=='all'&&c.dataset.category!==filter)})};search.addEventListener('input',apply);document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>{const selected=x===b;x.classList.toggle('active',selected);x.setAttribute('aria-pressed',String(selected))});apply()}))}
function setupContact(){const f=document.getElementById('contactForm');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(f),subject=encodeURIComponent('KKGT website inquiry — '+d.get('type')),body=encodeURIComponent(`Name: ${d.get('name')}\nCompany: ${d.get('company')}\nCountry: ${d.get('country')}\nEmail: ${d.get('email')}\nPhone: ${d.get('phone')}\nInquiry: ${d.get('type')}\nEstimated quantity: ${d.get('quantity')}\n\n${d.get('message')}`);location.href=`mailto:info@kkgtimportexport.com?subject=${subject}&body=${body}`})}
const desktop=document.getElementById('desktopNav'),mobile=document.getElementById('mobileNav');nav.forEach(([label,path])=>{const href=BASE+(path?'/'+path:'/');desktop.insertAdjacentHTML('beforeend',`<a class="route" data-path="${path}" href="${href}">${label}</a>`);mobile.insertAdjacentHTML('beforeend',`<a class="route" data-path="${path}" href="${href}">${label}</a>`)});
const menu=document.getElementById('mobileMenu'),menuBtn=document.getElementById('menuBtn'),closeBtn=document.getElementById('closeBtn'),pageMain=document.querySelector('main'),pageFooter=document.querySelector('footer'),pageHeader=document.querySelector('header');let prevFocus;
function setPageInert(value){pageMain.inert=value;pageFooter.inert=value;pageHeader.inert=value}
function openMenu(){prevFocus=document.activeElement;menu.classList.add('open');document.body.classList.add('menu-open');menuBtn.setAttribute('aria-expanded','true');menuBtn.setAttribute('aria-label','Close menu');setPageInert(true);closeBtn.focus()}
function closeMenu(restore=true){if(!menu.classList.contains('open'))return;menu.classList.remove('open');document.body.classList.remove('menu-open');menuBtn.setAttribute('aria-expanded','false');menuBtn.setAttribute('aria-label','Open menu');setPageInert(false);if(restore&&prevFocus)prevFocus.focus()}
menuBtn.addEventListener('click',openMenu);closeBtn.addEventListener('click',()=>closeMenu());document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open'))closeMenu()});menu.addEventListener('keydown',e=>{if(e.key==='Tab'){const f=[...menu.querySelectorAll('a,button')],first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
bindRoutes();addEventListener('popstate',()=>render());
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;let ticking=false;addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{document.getElementById('header').classList.toggle('scrolled',scrollY>30);if(!reducedMotion){const heroImage=document.querySelector('.hero .visual img');if(heroImage){const offset=Math.min(scrollY*.045,34);heroImage.style.transform=`translate3d(0,${offset}px,0) scale(1.035)`}}ticking=false})},{passive:true});
render();
})();
