(()=>{
const BASE='/kkgt-new-website';
const IMAGES={"about-operations":"/kkgt-new-website/standalone/images/about-operations.svg","agrochemicals":"/kkgt-new-website/standalone/images/agrochemicals.svg","coffee-export":"/kkgt-new-website/standalone/images/coffee-export.svg","coffee-farming":"/kkgt-new-website/standalone/images/coffee-farming.svg","commodities":"/kkgt-new-website/standalone/images/commodities.svg","contact":"/kkgt-new-website/standalone/images/contact.svg","hero-coffee":"/kkgt-new-website/standalone/images/hero-coffee.svg","origin-djimmah":"/kkgt-new-website/standalone/images/origin-djimmah.svg","origin-lekempti":"/kkgt-new-website/standalone/images/origin-lekempti.svg","origin-limmu":"/kkgt-new-website/standalone/images/origin-limmu.svg","origin-sidama":"/kkgt-new-website/standalone/images/origin-sidama.svg","origin-yirgacheffe":"/kkgt-new-website/standalone/images/origin-yirgacheffe.svg","quality":"/kkgt-new-website/standalone/images/quality.svg","sustainability":"/kkgt-new-website/standalone/images/sustainability.svg"};
const nav=[['Home',''],['About','about'],['Coffee Export','coffee-export'],['Agrochemicals','agrochemicals'],['Commodities','commodities'],['Sustainability','sustainability'],['Quality','quality'],['Contact','contact']];
const origins=[['Yirgacheffe','Southern Ethiopia','origin-yirgacheffe'],['Sidama','Southern Ethiopia','origin-sidama'],['Limmu','South-west Ethiopia','origin-limmu'],['Lekempti','Western Ethiopia','origin-lekempti'],['Djimmah','South-west Ethiopia','origin-djimmah']];
const products=[['BASECOR 80% WDG','Herbicide','WDG'],['CURTAIL 15.5% SC','Herbicide','SC'],['TABAN 80% WP','Fungicide','WP'],['PROLIGHT 45% SC','Fungicide','SC'],['AZADON 24% EC','Herbicide','EC'],['INSIDER 27% FS','Seed treatment','FS']];
const processes=[['Responsible sourcing','Supplier and lot information should be documented before preparation.'],['Selection and inspection','Incoming products are reviewed against agreed requirements.'],['Processing and preparation','Products are prepared according to commodity and buyer needs.'],['Quality verification','Checks confirm that the prepared lot aligns with agreed specifications.'],['Packaging and documentation','Packaging and commercial documentation are coordinated.'],['Shipment coordination','Dispatch and buyer communication are managed through the final stage.']];
const business=[['01','Green Coffee Export','Distinctive Ethiopian green coffee supported by sourcing, preparation and export coordination.','coffee-export','coffee-export'],['02','Agrochemical Import & Distribution','A verified crop-protection catalogue serving Ethiopian agriculture through organized distribution.','agrochemicals','agrochemicals'],['03','Coffee Farming','Coffee production rooted in Ethiopian origin, local knowledge and long-term agricultural value.','sustainability','coffee-farming'],['04','Oilseeds & Pulses','Selected Ethiopian commodities organized for commercial buyers and export inquiries.','commodities','commodities']];
const img=(key,alt,cls='')=>`<div class="visual ${cls}"><img src="${IMAGES[key]}" alt="${alt}"><span class="illustrative">Illustrative testing visual</span></div>`;
const hero=(eyebrow,title,intro,key)=>`<section class="page-hero">${img(key,alt(title))}<div class="page-hero-content reveal"><span class="eyebrow light">${eyebrow}</span><h1>${title}</h1><p>${intro}</p></div></section>`;
const alt=s=>s.replace(/<[^>]+>/g,'');
const heading=(eye,title,intro='')=>`<div><span class="eyebrow">${eye}</span><h2>${title}</h2>${intro?`<p class="body-copy" style="margin-top:20px;max-width:700px">${intro}</p>`:''}</div>`;
function home(){return `<section class="hero">${img('hero-coffee','Illustrative Ethiopian coffee landscape')}<div class="hero-content reveal"><span class="eyebrow light">Ethiopian agriculture · International trade</span><h1>From Ethiopian soil<br>to global markets.</h1><p>KKGT connects agricultural production, crop inputs and export opportunities through four focused business areas.</p><div class="actions"><a class="button orange" href="#business">Explore our business ↓</a><a class="button ghost route" href="${BASE}/contact">Contact KKGT ↗</a></div></div><div class="hero-foot"><span>KKGT Import Export</span><span>Testing website</span></div></section>
<section class="section"><div class="wrap intro-grid"><div class="reveal">${heading('About KKGT','An Ethiopian agricultural company built for sustainable growth.')}</div><div class="reveal"><p class="lead">KKGT works across green coffee export, agricultural inputs, coffee farming and selected oilseeds and pulses.</p><p class="body-copy">The redesigned test site focuses on buyer clarity, credible content, smooth performance and mobile usability.</p><a class="text-link route" href="${BASE}/about">Learn about KKGT ↗</a></div></div><div class="wide reveal" style="position:relative">${img('about-operations','Illustrative agricultural operations','about-visual')}<div class="image-note"><strong>1999 E.C.</strong><span>Establishment year stated on the existing website; confirm before official launch.</span></div></div></section>
<section class="dark-section" id="business"><div class="wide"><span class="eyebrow light">Four connected businesses</span><h2>Agricultural capability across the value chain.</h2><div class="business-grid">${business.map(b=>`<article class="business-card reveal"><div class="copy"><span class="num">${b[0]}</span><h3>${b[1]}</h3><p>${b[2]}</p><a class="text-link route" style="color:#fff" href="${BASE}/${b[3]}">Explore this business ↗</a></div>${img(b[4],`Illustrative ${b[1]} visual`)}</article>`).join('')}</div></div></section>
<section class="section origins"><div class="wide"><div class="section-head reveal">${heading('Coffee origins','Distinct origins. Exceptional Ethiopian coffee.')}<p>Origin details, grades, processing methods and availability must be confirmed from KKGT records.</p></div><div class="origin-row">${origins.map((o,i)=>`<article class="origin-card reveal">${img(o[2],`Illustrative ${o[0]} origin landscape`)}<div class="origin-copy"><span>0${i+1} · ${o[1]}</span><h3>${o[0]}</h3><p>Origin-inspired visual; not presented as a specific KKGT farm.</p></div></article>`).join('')}</div></div></section>
<section class="section"><div class="wrap">${heading('Export process','Prepared with care. Explained with clarity.','The process below is a structured draft and should be aligned with the company’s actual workflow.')}<div class="process-grid" style="margin-top:55px"><div class="reveal">${img('quality','Illustrative coffee quality inspection','process-visual')}</div><div class="steps">${processes.map((s,i)=>`<article class="step reveal"><span>0${i+1}</span><div><h3>${s[0]}</h3><p>${s[1]}</p></div></article>`).join('')}</div></div></div></section>
<section class="section" style="background:var(--ivory)"><div class="wide"><div class="products-head reveal">${heading('Agricultural inputs','A neutral, searchable product preview.','Real packshots and approved technical details will replace these non-packaging cards.')}<a class="text-link route" href="${BASE}/agrochemicals">View full catalogue ↗</a></div><div class="product-grid">${products.slice(0,4).map(p=>productCard(p)).join('')}</div></div></section>
<section class="evidence"><div class="reveal">${img('sustainability','Illustrative Ethiopian agricultural training')}</div><div class="evidence-copy reveal"><span class="eyebrow light">Evidence before claims</span><h2>Growth that can be documented.</h2><p>The final site should show real project locations, dates, participants and outcomes instead of generic sustainability claims.</p><a class="button ghost route" style="align-self:flex-start;margin-top:28px" href="${BASE}/sustainability">Explore sustainability ↗</a></div></section>
<section class="section"><div class="wrap">${heading('Quality and documentation','Trust should come from evidence.','Simulated certificates have been removed. Official files can be added only after KKGT verifies the issuer, title and validity.')}<div class="quality-list"><article class="quality-item reveal"><span>01</span><h3>Inspection</h3><p>Explain the real checks used at relevant operational stages.</p></article><article class="quality-item reveal"><span>02</span><h3>Traceability</h3><p>Connect suppliers, lots and documents where the process supports it.</p></article><article class="quality-item reveal"><span>03</span><h3>Documents</h3><p>Provide approved records to qualified buyers upon request.</p></article></div></div></section>
<section class="cta-band"><div class="wrap cta-inner reveal"><h2>Start the right agricultural conversation.</h2><a class="button orange route" href="${BASE}/contact">Contact KKGT ↗</a></div></section>`}
